### PR TITLE
Updated for OpenCV 3 and skimage > 0.17 and python 3

### PR DESCRIPTION
**Pull request by xkunglu**
Changed skimage.data.lena() to .camera() as lena was removed due to copyright 
https://github.com/scipy/scipy/pull/5162

added cv2 version check to handle name space changes.

changed  <> for the equivalent !=, former not working in python 3.6

### CODE REVIEW

**Comment by xkunglu** [comment]
hey ruanxiang,

As you saw i branched it to add a setup. I tried to change the least amount
of things, If you want to edit the setup file to correct credits, or
whatever, please do. If you want me to do a pull request in the new state,
let me know.  I am just trying different ways to aid in image segmentation
and i find it easier to just run a python setup or pip install . on any
code that i test.

thanks for the depot.

**Comment by ruanxiang** [comment]
Hello, xkunglu

Thank you so much for contributing MR python.

I am definitely a lazy guy to maintain my code, so appreciate your work!
Yes, please send me a pull request in the new state.

Thank you again!

Best regards,

**Comment by xkunglu** [comment]
Hey Xiang, I tried to do a pull request, i dont know if it took hold, if
not ill try again.
cheers
xk

**Comment by ruanxiang** [comment]
Hi, xkunglu

Actually I am waiting for your pull request, but didn't receive any notification from GitHub. Have I missed something? 

Could you please try again?

**Comment by xkunglu** [comment]
sorry Xiang, Im having github issues. Ill read up on whats my problem then
do a new pull request.

**Comment by xkunglu** [comment]
never mind, it seems the pull request did work. Sorry again, Im new to
github. Also I dont read email often, as you see. thank you! I will fix a
few other things in there - like dependencies, etc, then pull again. But I
dont look at this project often.

**Comment by ruanxiang** [comment]
Hi, xkunglu

Thank you for your great work!

best regards,

**Comment by xkunglu** [comment]
well, thank you, im just trying to make it simpler for me to use the code
you built. - tested it in ubuntu 16.04 on blank conda environment,  I made
another pull request for simpler install, information. I havent tested it
with live camera but i will, eventually - not yet as im working on other
projects.
xk

**Comment by ruanxiang** [comment]
Thank you so much for your contribution! Just merged your push. I also add some additional explanation in README about how to install wxpython under pyenv

**Pull request merged**
